"""add_sheet_name_to_data_files

Revision ID: 0cd50c3c8ec1
Revises: 527e0716ad77
Create Date: 2026-05-26 12:51:45.873320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd50c3c8ec1'
down_revision: Union[str, Sequence[str], None] = '527e0716ad77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_files', sa.Column('sheet_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_files', 'sheet_name')
    # ### end Alembic commands ###
