"""add original_filename to data_files

Revision ID: 2514c22a7e7f
Revises: 36511212eca6
Create Date: 2026-05-26 11:28:06.627229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2514c22a7e7f'
down_revision: Union[str, Sequence[str], None] = '36511212eca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_files', sa.Column('original_filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_files', 'original_filename')
    # ### end Alembic commands ###
