"""add_status_to_execution_history

Revision ID: 527e0716ad77
Revises: 2514c22a7e7f
Create Date: 2026-05-26 11:45:34.157190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527e0716ad77'
down_revision: Union[str, Sequence[str], None] = '2514c22a7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_history', sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='projectstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_history', 'status')
    # ### end Alembic commands ###
