"""add marker_preview to split_runs

Revision ID: e02a9df74790
Revises: e5a9bfd68e9e
Create Date: 2026-04-28 16:59:18.244164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e02a9df74790'
down_revision: Union[str, Sequence[str], None] = 'e5a9bfd68e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('split_runs', sa.Column('marker_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('split_runs', 'marker_preview')
    # ### end Alembic commands ###
